# Generated by Django 3.2 on 2026-09-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetCreditBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('member_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=45)),
                ('cvd_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cvd_name', models.CharField(blank=True, default='', max_length=255)),
                ('village_ids', models.JSONField(blank=True, default=list)),
                ('village_names', models.TextField(blank=True, default='')),
                ('cvgp_message', models.TextField(blank=True, default='')),
                ('fc_message', models.TextField(blank=True, default='')),
                ('resolution_warning', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'internet credit beneficiary',
                'verbose_name_plural': 'internet credit beneficiaries',
                'ordering': ['cvd_name', 'member_name'],
            },
        ),
        migrations.CreateModel(
            name='InternetCreditConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('cvgp', 'CVGP member'), ('fc', 'FC/AC')], max_length=10)),
                ('confirmed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('signature', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('grm_mobile', 'MGP mobile'), ('cdd_mobile', 'DCC mobile')], default='grm_mobile', max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='internet_credits.internetcreditbeneficiary')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_credit_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'internet credit confirmation',
                'verbose_name_plural': 'internet credit confirmations',
                'ordering': ['confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='InternetCreditCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period', models.DateField(help_text='Any day of the month; stored as the 1st.', verbose_name='month')),
                ('sent_date', models.DateField(verbose_name='package sending date')),
                ('package_label', models.CharField(default='3 Go valables 30 jours', max_length=100, verbose_name='package')),
                ('amount', models.PositiveIntegerField(default=3000, verbose_name='amount (FCFA)')),
                ('cvgp_message_template', models.TextField(default="CVGP du CVD {cvd} a bien reçu le crédit internet pour le mois de {mois} {annee}, et j'en confirme sa réception", verbose_name='CVGP checkbox message')),
                ('fc_message_template', models.TextField(default="CVGP du CVD {cvd} a bien reçu le crédit internet pour le mois de {mois} {annee}, et j'en confirme sa réception", verbose_name='FC/AC checkbox message')),
                ('attestation_text', models.TextField(default='Je confirme que ces CVD ont bien reçu le forfait internet ({forfait}) pour le mois de {mois} {annee}.', verbose_name='monthly PDF attestation')),
                ('agreement_text', models.TextField(default='Je confirme que le CVGP du CVD {cvd} a bien reçu le forfait internet ({forfait}) pour le mois de {mois} {annee}.', verbose_name='CVD PDF agreement message')),
                ('signatory_name', models.CharField(blank=True, default='', max_length=255, verbose_name='signatory name')),
                ('signatory_title', models.CharField(blank=True, default='', max_length=255, verbose_name='signatory title')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'internet credit campaign',
                'verbose_name_plural': 'internet credit campaigns',
                'ordering': ['-period'],
            },
        ),
        migrations.AddField(
            model_name='internetcreditbeneficiary',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='internet_credits.internetcreditcampaign'),
        ),
        migrations.AddField(
            model_name='internetcreditbeneficiary',
            name='cvgp_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_credit_beneficiaries', to=settings.AUTH_USER_MODEL, verbose_name='CVGP member'),
        ),
        migrations.AddConstraint(
            model_name='internetcreditconfirmation',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('beneficiary', 'role', 'confirmed_by'), name='unique_active_internet_credit_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='internetcreditcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('period',), name='unique_active_internet_credit_period'),
        ),
        migrations.AddConstraint(
            model_name='internetcreditbeneficiary',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('campaign', 'cvgp_member'), name='unique_active_internet_credit_beneficiary'),
        ),
    ]
