# Generated by Django 3.2 on 2026-07-17 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0002_auto_20260717_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_code', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subproject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subproject_description', models.TextField(blank=True, null=True)),
                ('vote_ym', models.IntegerField(default=0)),
                ('vote_yf', models.IntegerField(default=0)),
                ('vote_mm', models.IntegerField(default=0)),
                ('vote_mf', models.IntegerField(default=0)),
                ('vote_om', models.IntegerField(default=0)),
                ('vote_of', models.IntegerField(default=0)),
                ('adl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_projects', to='issue.adl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ordinal', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('adl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='issue.adl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ordinal', models.IntegerField(default=0)),
                ('task_type', models.CharField(choices=[('multiple_list_activity', 'Multiple list activity'), ('vote_activity', 'Vote activity'), ('input_activity', 'Input activity'), ('document', 'Document')], default='document', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('in-progress', 'In progress'), ('completed', 'Completed')], default='not-started', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('bp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='budgeting.phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_date', models.DateTimeField()),
                ('bp_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='budgeting.bpproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
