# Generated by Django 3.2 on 2026-07-17 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import issue.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # `administrativelevels` n'a et n'aura jamais de migration (base `mis` externe, gérée par
        # le projet `cosomis` — voir grm/routers.py). Cette référence `__first__` est nécessaire
        # même sans migration réelle : Django s'en sert pour résoudre la FK paresseuse
        # `Issue.administrative_region` via le mécanisme "unmigrated app" (état de l'app pris
        # depuis administrativelevels/models.py directement plutôt que depuis un historique de
        # migrations). Ne pas la retirer — voir grm/test_settings.py pour la contrepartie côté
        # tests (l'alias 'mis' y est exclu de DATABASES pour éviter que le test runner tente de
        # construire un plan de migration multi-base sur cette app).
        ('administrativelevels', '__first__'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=issue.models.Attachment._upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('internal_code', models.CharField(max_length=100, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_increment_id', models.IntegerField()),
                ('description', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('citizen', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_medium', models.CharField(blank=True, max_length=50, null=True)),
                ('citizen_type', models.CharField(blank=True, max_length=50, null=True)),
                ('citizen_group_1', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_group_2', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_or_group', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(default='mobile', max_length=20)),
                ('publish', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('notification_send', models.BooleanField(default=True)),
                ('ongoing_issue', models.BooleanField(default=False)),
                ('event_recurrence', models.BooleanField(default=False)),
                ('resolution_days', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField()),
                ('intake_date', models.DateTimeField()),
                ('issue_date', models.DateTimeField()),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('reject_date', models.DateTimeField(blank=True, null=True)),
                ('research_result', models.TextField(blank=True, null=True)),
                ('original_description', models.TextField(blank=True, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('administrative_region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_info', models.JSONField(blank=True, null=True)),
                ('structure_in_charge', models.JSONField(blank=True, null=True)),
                ('contact_information', models.JSONField(blank=True, null=True)),
                ('commune', models.JSONField(blank=True, null=True)),
                ('administrative_region', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='administrativelevels.administrativelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueAgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('confidentiality_level', models.CharField(blank=True, max_length=50, null=True)),
                ('redirection_protocol', models.IntegerField(blank=True, null=True)),
                ('assigned_department', models.JSONField(blank=True, null=True)),
                ('assigned_appeal_department', models.JSONField(blank=True, null=True)),
                ('assigned_escalation_department', models.JSONField(blank=True, null=True)),
                ('administrative_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('final_status', models.BooleanField(default=False)),
                ('initial_status', models.BooleanField(default=False)),
                ('rejected_status', models.BooleanField(default=False)),
                ('open_status', models.BooleanField(default=False)),
                ('unresolved_status', models.BooleanField(default=False)),
                ('eligible_status', models.BooleanField(default=False)),
                ('not_eligible_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.CharField(default='reason', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasons', to='issue.attachment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='issue.issue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueStatusStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_status_stories', to='issue.issue')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_status_stories', to='issue.issuestatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_issue_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.issueagegroup'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issue.issuecategory'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issue.issuetype'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issue.issuestatus'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issue.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issue.issue'),
        ),
        migrations.CreateModel(
            name='Adl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legacy_couch_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('administrative_region_ids', models.JSONField(blank=True, default=list)),
                ('additional_administrative_region_ids', models.JSONField(blank=True, default=list)),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adl_representations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
