# Generated by Django 3.2 on 2026-07-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
        ('issue', '0002_auto_20260717_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='budgeting.task'),
        ),
    ]
