# Generated by Django 3.2 on 2026-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20260717_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='adl',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='adl_photos/'),
        ),
        migrations.AddField(
            model_name='adl',
            name='village_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
