# Generated by Django 3.2 on 2026-07-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20260717_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adl',
            name='photo',
        ),
    ]
