# Generated by Django 3.2 on 2026-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_remove_adl_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='accepted_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='closed_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='rejected_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
