# Generated by Django 3.2 on 2026-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_auto_20260718_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='legacy_bd_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='legacy_couch_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
