# Generated by Django 3.2 on 2026-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_auto_20260718_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='adl',
            name='additional_smallest_administrative_level_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adl',
            name='smallest_administrative_level_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
