# Generated by Django 3.2 on 2026-07-24 09:13

from django.db import migrations, models


def mark_existing_stories_as_notified(apps, schema_editor):
    """Les entrées d'historique déjà existantes (migrées depuis CouchDB ou créées avant cette
    fonctionnalité) ne doivent pas déclencher un email rétroactif dès le premier passage de
    `dashboard.tasks.send_issue_status_notifications` — seules les entrées créées à partir de
    maintenant doivent notifier (même principe que `Issue.notification_send=True` par défaut pour
    ne pas notifier les issues historiques)."""
    IssueStatusStory = apps.get_model('issue', 'IssueStatusStory')
    IssueStatusStory.objects.update(email_notified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_auto_20260721_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatusstory',
            name='email_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_stories_as_notified, migrations.RunPython.noop),
    ]
