# Generated by Django 3.2 on 2026-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_issuestatusstory_email_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='notification_send',
            field=models.BooleanField(default=False),
        ),
    ]
