# Generated by Django 3.2 on 2023-10-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230609_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentworker',
            name='administrative_ids',
            field=models.JSONField(null=True, verbose_name='administrative levels'),
        ),
    ]
