# Generated by Django 3.2 on 2026-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_governmentworker_administrative_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentworker',
            name='additional_administrative_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional administrative levels'),
        ),
    ]
