# Generated by Django 3.2 on 2023-10-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategpryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('issue_category_id', models.IntegerField(choices=[(1, '1- Demande de renseignement ou de précision'), (2, '2- Relative à un autre programme ou projet'), (3, '3- Perception par une communauté ou une personne qu’elle est était injustement exclues de participer au projet'), (4, '4- Allégation de corruption, de détournement de fonds ou de biais dans les marchés publiques (sensible)'), (5, '5- Préjudices environnementaux ou sociaux causés aux communautés par les interventions du projet'), (6, '6- Déviation de buts ou procédure du projet y compris les allégations de mauvaise performance ou comportement incorrects de personnel du projet'), (7, '7- Violence basée sur le genre (sensible)')], verbose_name='Category')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
