# Generated by Django 3.2 on 2023-11-06 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privacy', '0002_auto_20231003_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueCategpryPassword',
            new_name='IssueCategoryPassword',
        ),
        migrations.AlterModelOptions(
            name='issuecategorypassword',
            options={'verbose_name': 'Category Password', 'verbose_name_plural': 'Categories password'},
        ),
    ]
